#!/usr/bin/env python3
"""Generate the slate block of `paper/PROJECT_FACTS.md` from the artefacts.

    ./.venv/bin/python platform/build_project_facts.py           -> rewrite the block
    ./.venv/bin/python platform/build_project_facts.py --check   -> exit 1 if it is stale

The defect this exists for
--------------------------
`paper/PROJECT_FACTS.md` is the fact sheet the manuscript's drafters worked from, and its
first line calls itself the ground truth. One bullet in it was typed by hand:

    - Slate: 8 pre-registered studies, 25 hypotheses (13 confirmed, 11      [SLATE-COUNT-HISTORICAL]
      falsified, 1 not tested); 5 decided by a test statistic, 19 by a      [SLATE-COUNT-HISTORICAL]
      threshold                                                            [SLATE-COUNT-HISTORICAL]

That was true when it was written. Study #12, `interface-null-positive-control-v1`, was
registered on 2026-08-22 and added three hypotheses, and the bullet did not move. Six drafted
sections copied it, so the manuscript ended up narrating #12 in Results and Discussion -- "a
later positive control" -- and then counting a slate that does not contain it, which reads as
post-hoc work sitting outside the protocol. It is the opposite: #12 is the only study in the
slate whose audit records `confirmatory = true`.

A fact sheet that is typed is a fan-out point with no back-reference: correcting `slate.json`
does not reach it, and nothing in the repository could see that it had been left behind. So
the counts are no longer typed. Every number between the markers is read at run time from
`data/slate.json` (generated by `platform/build_slate.py` from the study artefacts) and from
the `analysis.prespec_audit` blocks of `data/study_*.json`.

Scope
-----
This owns ONE region of the file, delimited by the two markers below. The rest -- the target
table, the candidate table, the headline measurements, the methods list -- stays hand-
maintained. A generator that rewrote the whole file would have to re-derive prose it does not
own, which is how a generator starts inventing.

`paper/` is not published by this repository (see the block at the end of `.gitignore`), so
in a clone this script has no target. It says so and exits 0 rather than raising: an absent
subject is not a stale fact sheet, and a traceback would read like one. For the author, whose
working tree has `paper/`, it behaves exactly as it always did.

Nothing here writes to `prespec/` or `data/superseded/`, which are records of what was true
then and are never rewritten.

The guard that catches the same defect on every other surface is
`platform/check_metadata_counts.py`; this generator makes one of its 35 surfaces incapable of
going stale, rather than merely detectable once it has.
"""

from __future__ import annotations

import json
import sys

from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TARGET = REPO / "paper" / "PROJECT_FACTS.md"

BEGIN = "<!-- GENERATED:slate — platform/build_project_facts.py owns everything between"
BEGIN_FULL = (
    BEGIN + " these\n     markers and rewrites it from data/slate.json and the per-study\n"
    "     analysis.prespec_audit blocks. Do not type a slate count here by hand. -->"
)
END = "<!-- /GENERATED:slate -->"


def facts() -> dict:
    """Every value read from the artefacts, none of them typed here."""
    slate = json.loads((REPO / "data" / "slate.json").read_text())
    c = slate["counts"]

    # The deviation ledger, recounted from the study artefacts rather than taken from a
    # summary: `analysis.prespec_audit.deviations` is the machine-detected list each study
    # carries, and it is the thing the manuscript's Limitations section claimed did not exist.
    devs, audited, seen = 0, 0, set()
    for f in sorted((REPO / "data").glob("study_*.json")):
        body = json.loads(f.read_text())
        a = body.get("analysis") or body
        if not a.get("verdicts"):
            continue          # an input file with no decisions is not a study of the slate
        sid = a.get("study_id")
        if sid in seen:
            raise SystemExit(f"two artefacts claim study_id {sid}; refusing to guess")
        seen.add(sid)
        audit = a.get("prespec_audit") or {}
        if "deviations" not in audit:
            raise SystemExit(f"{f.name} carries no prespec_audit.deviations list")
        audited += 1
        devs += len(audit["deviations"])

    if audited != c["studies"]:
        raise SystemExit(f"{audited} studies carry an audit but slate.json counts "
                         f"{c['studies']}; rebuild data/slate.json first")

    conf = [s for s in slate["studies"] if s.get("confirmatory") is True]
    sep = slate["separation_across_versions"]
    return {
        "counts": c,
        "deviations": devs,
        "audited": audited,
        "confirmatory": conf,
        "retained_versions": sep["n_versions"],
    }


def block(f: dict) -> str:
    c = f["counts"]
    conf = f["confirmatory"]
    who = ", ".join(f"#{s['slate_number']} ({s['study_id']})" for s in conf) or "none"
    lines = [
        BEGIN_FULL,
        "",
        f"- Slate: {c['studies']} pre-registered studies, {c['hypotheses']} hypotheses "
        f"({c['confirmed']} confirmed, {c['falsified']} falsified, "
        f"{c['not_tested']} not tested); {c['decided_by_a_test']} decided by a test "
        f"statistic, {c['decided_by_a_threshold']} by a threshold, "
        f"the two summing to the {c['decided']} that were decided",
        f"- {len(conf)} confirmatory study of {c['studies']}: {who} is the only one whose "
        f"audit records confirmatory = true; the other {c['studies'] - len(conf)} record at "
        "least one departure from their registered plan",
        f"- Deviation ledger: {f['deviations']} departures from plan are recorded across the "
        f"slate, machine-detected and listed per study in analysis.prespec_audit.deviations "
        f"({len(conf)} of the {f['audited']} audits is empty). The ledger exists and is "
        "compiled here; do not write that it is not",
        f"- H1 falsified in all {f['retained_versions']} retained versions",
        "",
        END,
    ]
    return "\n".join(lines)


def splice(text: str, new: str) -> str:
    i = text.find(BEGIN)
    j = text.find(END)
    if i == -1 or j == -1:
        raise SystemExit(f"{TARGET.relative_to(REPO)} has no GENERATED:slate block to fill; "
                         "add the two markers around the slate bullets first")
    return text[:i] + new + text[j + len(END):]


def main() -> int:
    if not TARGET.exists():
        # Not a failure. paper/ is the author's manuscript workspace and is not published
        # here, so a clone has nothing to write into. A skip that names its reason is the
        # honest report; a FileNotFoundError traceback would look like a defect in the data.
        print(f"SKIP — {TARGET.relative_to(REPO)} is not in this tree. paper/ is not "
              "published by this repository, so there is no fact sheet to generate.")
        return 0
    text = TARGET.read_text()
    want = splice(text, block(facts()))
    if "--check" in sys.argv:
        if want != text:
            print(f"STALE — {TARGET.relative_to(REPO)} slate block does not match the "
                  "artefacts. Run: ./.venv/bin/python platform/build_project_facts.py")
            return 1
        print(f"PASS — {TARGET.relative_to(REPO)} slate block matches data/slate.json and "
              "the per-study audits.")
        return 0
    TARGET.write_text(want)
    print(f"wrote the slate block of {TARGET.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
