#!/usr/bin/env python3
"""Guard: every hand-typed slate count must equal the artefacts it summarises.

The defect this exists for
--------------------------
`CITATION.cff`, `codemeta.json`, `biotools.json`, `.zenodo.json` and `docs/REGISTRATION.md`
all said, verbatim, "Eight studies were pre-registered under content hashes before any data
was seen." That was true when it was written. Study #12, `interface-null-positive-control-v1`,
was registered on 2026-08-22, and none of the five sentences moved -- so the citable record,
the DOI description, the bio.tools entry and the RRID submission block all described a slate
with the retraction study removed from it. `docs/RELEASE_NOTES_v1.0.0.md` and `paper/` carry
the same count with the verdict totals attached to it.

Why the guards already in the repository could not see it
---------------------------------------------------------
The prose guard that used to run beside this one bound every numeral in the manuscript to an
artefact, and it reported 10 passed / 0 failed on a document that says "8 pre-registered
studies and 25 hypotheses". Two reasons, both deliberate: `8` and `25` were members of the
22,054-string set it collected from `data/`, and it exempted small counts as the ordinary
vocabulary of prose. Neither was a bug. No
membership test can distinguish a number with no basis from a number whose basis has MOVED --
`8` still sources correctly, to last month's slate.

That is the gap here: this guard does not ask whether a number appears somewhere in `data/`.
It asks whether the number standing next to the word `studies` is *the current* study count.

What it binds to
----------------
Nothing in this file is a constant. Every expected value is read at run time from
`data/slate.json` (itself generated by `platform/build_slate.py` from the artefacts),
`len(glob('prespec/*.json'))` and `len(verify_all.SUITES)`.

The number-word half is load-bearing
------------------------------------
Three of the four metadata files spelled it "Eight". A numeral-only scan finds nothing, which
is exactly why this went unnoticed while a repository full of numeric guards passed. Both
forms are scanned.

Scope, and what is deliberately NOT bound
-----------------------------------------
* The bare phrase "N study artefacts" is not bound either, and the reason is instructive:
  `docs/REGISTRATION.md` uses it to count the three artefacts that carry ChEMBL's share-alike
  licence, which is a different quantity wearing the same words. `.zenodo.json` now says
  "the artefacts of 9 studies", which this guard does bind. A pattern that cannot tell two
  meanings apart should be narrowed until it can, not left to cry wolf.
* Candidate counts ARE bound now, and why they were not is worth keeping. "13 candidates" was
  a live scientific question -- thirteen candidate-receptor constructs cover twelve distinct
  peptides, because de-duplication was applied on (peptide, target), which does not collapse
  one peptide declared against two receptors -- and a guard must not settle a scientific
  question by picking a side. The screens settle it themselves now:
  `analysis.peptide_multiplicity` in `data/study_candidate_screen.json` and
  `data/study_msa_specificity.json` records both counts, derived from the stored rows, and the
  two must agree or this guard refuses to run. So both numbers are read from those blocks like
  every other expected value. What is bound is the two unambiguous phrasings, "N
  candidate-receptor constructs" and "N distinct peptides", plus the one that was wrong on five
  surfaces: "N distinct candidates/designs" is bound to the PEPTIDE count, because the word
  "distinct" makes that sentence a claim about molecules rather than about rows.
* `prespec/**` and `data/superseded/**` are not scanned at all. A registered plan and a
  superseded artefact are records of what was true then; rewriting one to match today would
  destroy the property they exist for.
* Korean editions are scanned with the same English triggers, which will not fire on Korean
  labels. This gap is now OPEN, and is recorded rather than papered over. It used to be
  covered from the other side by a parity guard that required every number stated in English
  to appear in the Korean, so a corrected English count forced the Korean to follow. That
  guard watched report editions this repository no longer publishes and is no longer part of
  it. Nothing in a clone carries a Korean count today; if one ever returns, the parity check
  has to return with it.

Escape hatch
------------
Exactly one, and it must be visible: a line containing the token `SLATE-COUNT-HISTORICAL` is
skipped, for prose that deliberately quotes a superseded count (a release note frozen to what
that release said, a paragraph describing what a published DOI record still reads). Use it
rarely; a count with no such marker is a claim about the repository as it stands now.
"""

from __future__ import annotations

import fnmatch
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

#: Surfaces where a slate count is typed by hand and read by someone who will not check it.
#: `docs/REGISTRATION.md` matters more than the others: two of its blocks are copy-paste
#: submissions to bio.tools, SciCrunch/RRID and the Research Software Directory, so a wrong
#: count there does not stay in the repository.
SURFACES: tuple[str, ...] = (
    "CITATION.cff",
    "codemeta.json",
    "biotools.json",
    ".zenodo.json",
    "docs/REGISTRATION.md",
    "README.md",
    # The workbench itself, which was on no guard surface list at all -- not this one, and
    # not either of the two prose guards that ran alongside it then. Every count it displays
    # is read from data/, so
    # the assumption was that it could not state a stale one. It could: the Slate tab's
    # notice carried a hand-written bold heading, "Not one study in this slate is
    # confirmatory", directly above the generated paragraph naming #12 as the exception and
    # directly below a stat card reading "1 confirmatory". The page contradicted itself in
    # three lines and nothing was looking at the page.
    "app.js",
    "index.html",
    # Added by the derivation experiment described under "Derived or declared" below, not by
    # anyone reading the file. `verify_all.py` is the entry point the README tells a reader to
    # run, `platform/check_retractions.py` has watched it since it was written, and this guard
    # did not -- so "the five suites whose success is exit 0" sat in it while SUITES held
    # twelve, eleven of them expecting 0. Third instance of the same mechanism, in the one
    # file whose job is to run the guards that exist to catch it.
    "verify_all.py",
)

#: Surfaces where only SOME count keys are bound, and the reason each exclusion exists.
#:
#: `README.md` is the most-read surface in the repository and it states the slate size, the
#: plan count and the suite count -- including in two badges, which is where a reader looks
#: first and where no scan had ever looked at all. It also, legitimately, counts things that
#: wear the same nouns as the slate totals, and binding those would make the guard cry wolf
#: on correct prose. Every one of these is a real sentence in the file today:
#:
#:   "round-2 re-classified all three hypotheses as threshold criteria"   one STUDY's hypotheses
#:   "All three hypotheses confirmed."                                     one study's, again
#:   "Slate #12 falsified it and that clause is retracted."                a study number
#:   "across the screen's six retained versions"                           one study's versions
#:   "that run reported nine distinct designs, and the current v8 ..."     a superseded version
#:
#: So README is bound to the three keys that have no per-study meaning: a study is either in
#: the slate or not, a plan is either registered or not, and a suite either runs or does not.
#: Narrowing the surface is the honest move; the alternative is a guard nobody believes.
#: A fourth key was added after a cold reader took "including the eleven falsifications" out
#: of the How-to-cite block as this project's headline: `falsifications`, the noun. It is
#: bound here and `falsified`, the adjective, still is not -- which is exactly why they are
#: separate keys. The adjective collides with a study number in this file; the noun collides
#: with nothing, and the sentence it guards is the one a citer reads.
#:
#: IS THE RESTRICTION STILL RIGHT? In kind, yes; in reach, it was not, and the same reader
#: who found `falsifications` would have found this. README's summary table -- line 90, the
#: first quantitative statement a visitor reads -- says "9 pre-registered studies, 28
#: hypotheses of which 27 are decided". `studies` was bound there. `hypotheses` was not, and
#: neither was the decided total, because `hypotheses` legitimately counts one study's three
#: on three other lines of the same file. So the most-read count in the repository was
#: unbound on a technicality about a different sentence.
#:
#: A whole-key exclusion is too blunt an instrument: it excludes the phrasings that CANNOT
#: collide along with the one that can. The fix is the one already proven on
#: `falsified`/`falsifications` -- split the key, so the collision-free phrasing gets bound
#: where the colliding one cannot be. `hypotheses_in_roster` binds only the form that names
#: the hypothesis count in the same breath as the study count, which no per-study sentence
#: can wear; `decided` binds "of which N are decided", which is a slate-wide split by
#: construction. Both are added to README here. `confirmations` is the same move for
#: `confirmed`, whose adjective collides with "All three hypotheses confirmed."
#:
#: What stays excluded splits in two, and the split is worth stating because only half of it
#: is evidence:
#:
#:   demonstrated. `hypotheses` reads 3 on three lines, `falsified` reads 12 off "Slate #12
#:   falsified it", `retained_versions` reads 6, `distinct_peptides` reads 9. Those four
#:   sentences are in SELF_TEST_RESTRICTED below, so the exclusion cannot quietly widen back
#:   and a rewrite of the prose that removes the collision will show up as a stale test.
#:
#:   by principle, with no collision in the file today. `confirmed`, `not_tested`, the two
#:   decision kinds, `deviations`: each counts a quantity that EXISTS per study, so README
#:   is one per-study table away from a false positive. They stay out because the shape of
#:   the file invites the sentence, not because the sentence is already there.
#:
#: And the honest caveat on the noun forms: `falsifications` is bound on README and NOT on
#: app.js, because app.js line 1153 really does say "only two falsifications in the slate"
#: while quoting a misreading it corrects. Nominalisation does not make a count immune to a
#: per-study reading -- it only happens to have no per-study reading on the surfaces where it
#: is bound. That is a per-file judgement, checked against the file, not a principle. Anyone
#: widening this table should run the probe the way it was run here: scan the surface with
#: every key enabled and read what the excluded keys actually report.
#: `app.js` and `index.html` are bound to the same three keys as README, plus the two
#: confirmatory ones and the peptide counts -- the claims that have no per-study meaning and
#: that these two files actually make. They are excluded from the rest for a reason a scan of
#: them makes obvious: `app.js` carries JS comments that quote superseded sentences in order
#: to explain why the code no longer contains them, and it refers to studies by number.
#: "Study #12 falsified that clause" reads to the `falsified` rule as a slate total of 12.
RESTRICTED: dict[str, frozenset[str]] = {
    "README.md": frozenset({"studies", "plans", "suites", "falsifications",
                            "confirmations", "hypotheses_in_roster", "decided"}),
    "app.js": frozenset({"studies", "studies_confirmatory", "plans", "suites",
                         "distinct_peptides", "screened_constructs"}),
    "index.html": frozenset({"studies", "studies_confirmatory", "plans", "suites",
                             "distinct_peptides", "screened_constructs"}),
    # fnmatch, so one entry covers the whole generator family.
    "platform/build_*.py": frozenset({"studies", "studies_confirmatory", "plans", "suites"}),
}


#: ============================================================================================
#: DERIVED OR DECLARED -- the question this list keeps losing, and what was measured
#: ============================================================================================
#:
#: Three times now a count has gone stale on a surface this guard did not enumerate.
#: `app.js` and `index.html` (the workbench contradicted itself in three lines), and
#: `verify_all.py` ("the five suites whose success is exit 0", while SUITES held twelve).
#: Each was fixed by appending a line to SURFACES. That is a repair with a known half-life:
#: an enumerated list is a snapshot of who was paying attention on the day it was written.
#:
#: So the honest question is whether the list can be DERIVED -- every tracked text file,
#: minus a stated exemption list -- rather than declared. It was tried before it was
#: answered. Three measurements, all reproducible from this tree:
#:
#: (1) "Every TRACKED text file" is the wrong basis, and not marginally. `.gitignore` ends
#:     with `paper/`, and `docs/*.html`, `docs/*.docx`, `docs/*.pptx` are ignored above it.
#:     The whole manuscript tree is untracked: `paper/PROJECT_FACTS.md`,
#:     `paper/sec_*.md`, `paper/deck_copy*.json` -- 35 files this guard watches TODAY through
#:     SURFACE_GLOBS. Deriving from the index would UNWATCH the surface that carried
#:     "no ledger of such departures is compiled here", which is the worst single sentence
#:     the WORDED table has ever caught. A derivation is only as good as its universe, and
#:     this repository's universe is not the git index.
#:
#: (2) Deriving from the FILESYSTEM instead is strictly wider, and the width is the problem.
#:     Pointing `scan()` at every non-binary file outside `.git/` and the virtualenvs:
#:     2,369 files, 514 count claims bound, 299 reported stale. Restricting to the tree
#:     minus the directories this project already treats as records (`runs/`, `prespec/`,
#:     `data/superseded/`, `reviews/`, `research/`, `memory/`, `mas/`): 428 files, 348
#:     claims, 133 reported stale. Of those 133, the ones that were real defects were the
#:     two sentences in `verify_all.py`. Roughly one true positive for every forty-four false
#:     ones -- and the false ones are not noise to be tuned away, they are correct prose:
#:     `reviews/audit_r1.json` quoting the stale sentence it is reporting, `retractions.jsonl`
#:     holding the withdrawn wording by construction, `research/np_scaleout.json` saying
#:     "989 confirmed" about something else entirely, and this file's own rule table.
#:     A content guard at that ratio is a guard nobody believes, and a guard nobody believes
#:     is worse than no guard: it trains its readers to skip the output.
#:
#: (3) But the derivation DID find something. `verify_all.py` -- the file the README tells a
#:     reader to run, watched by `check_retractions.py` since the day it was written and by
#:     this guard never -- carried a live stale count that three rounds of enumeration and
#:     two independent readers had walked past. Enumeration is not merely imperfect here; it
#:     failed on the entry point.
#:
#: THE ANSWER, then, is that the question conflates two things a derived list is good for,
#: and they have opposite economics:
#:
#:     CONTENT   which files' counts get bound. Derivation is useless: 44:1 false positives,
#:               because most files that state a number are records, quotations or code.
#:               Stays declared, and stays narrow, and each narrowing carries its reason.
#:
#:     COVERAGE  which files exist at all, and whether anyone has DECIDED about each one.
#:               Derivation is exact: a file is either on a surface list or matched by a
#:               stated exemption, and that question has no false positives because it is not
#:               about what the file says. This is the question enumeration answers "no" to
#:               silently, and it is the question that would have caught `app.js`,
#:               `index.html` and `verify_all.py` on the day each was created.
#:
#: `coverage()` below implements the second. It walks the tree, and every text file must be
#: either a surface of this guard or matched by an entry in `UNWATCHED` carrying a reason. A
#: new file is neither, so it fails the guard with "neither watched nor exempted" and the
#: person adding it makes the call. That is the whole cost: one triage decision per new text
#: file, paid by the person who is looking at the file, instead of a stale-count round paid
#: by whoever finds it eighteen months later.
#:
#: WHAT MAKES THE DECLARED LIST TRUSTWORTHY, given that it stays declared:
#:   * it cannot silently omit a file -- `coverage()` fails on anything unclassified;
#:   * it cannot silently omit a RULE -- `platform/tools/mutation_suite.py` enumerates
#:     `RULES`, `WORDED`, `SURFACES` and `SURFACE_GLOBS` from this module's own code and
#:     reports UNCOVERED for any entry no mutation targets;
#:   * every exemption states a reason next to itself, and `--coverage` prints how many
#:     count claims the exempt set would have raised, so an exemption that is quietly hiding
#:     a stale count is visible as a number rather than as nothing.
#: An enumerated list with those three properties is a list whose gaps are loud. That is a
#: different object from the list this guard started with, which had none of them.

#: (glob, why this file is not a count surface). Matched with `fnmatch` against the
#: repo-relative path, so `runs/*` needs its own recursive form -- see `_matches`.
#: Order is irrelevant; the first match wins only for the reason printed.
UNWATCHED: tuple[tuple[str, str], ...] = (
    # --- records of what was true then. Rewriting any of these destroys what they are for.
    ("prespec/*", "hash-locked registered plans; a plan is never rewritten after the fact"),
    ("data/superseded/*", "retained earlier artefacts, kept to record what was believed"),
    ("memory/ledger/*", "the append-only provenance ledger; a correction is a NEW record"),
    ("runs/*", "raw fold output, one directory per run; machine-written, never prose"),
    ("reviews/*", "adversarial review and adjudication transcripts -- records of what was "
                  "SAID, including the stale sentences being reported. Scanning them would "
                  "report every finding as the defect it reports"),
    ("research/*", "literature and scale-out notes about other people's numbers"),
    ("retractions.jsonl", "the retraction ledger; it holds the withdrawn wording by "
                          "construction, which is the point of it"),
    # --- the artefacts the counts are READ FROM. Binding a surface count to these would be
    # --- circular: `expected()` reads slate.json, so slate.json cannot be a surface.
    ("data/*.json", "the artefacts this guard reads its expected values FROM"),
    ("data/*.js", "the same artefacts, as the browser mirrors build_*.py emits"),
    ("data/*/*", "per-target and per-complex numeric arrays; no prose"),
    ("data/*/*/*", "per-target and per-complex numeric arrays; no prose"),
    # --- code that is neither a generator nor a document.
    ("platform/studies/*", "study drivers; every count they state is computed, not typed"),
    ("platform/cbc/*", "the inference and scoring library"),
    ("platform/tests/*", "the regression suite; it asserts on stale counts on purpose"),
    ("platform/tools/*", "the mutation suite; it PLANTS stale counts on purpose"),
    ("platform/check_*.py", "the guards themselves, this file among them; their rule tables "
                            "and self-tests quote every stale count deliberately"),
    ("platform/*.py", "dataset, structure and validation drivers"),
    ("memory/*.py", "the ledger implementation"),
    ("memory/tests/*", "the ledger regression suite"),
    ("mas/*", "the agent definitions this project was built with"),
    (".agents/*", "agent definitions"),
    (".claude/*", "local tool configuration, not published"),
    # --- documents whose slate counts are generated, or which state none.
    ("memory/views/*", "generated renderings of the ledger"),
    ("memory/*.md", "the ledger's own design and spec documents"),
    ("docs/*.html", "built decks; the source they are built from is watched above"),
    ("docs/REFERENCES.json", "a bibliography"),
    # NOT `paper/*`. The manuscript tree is where the stale slate sentence lived, and a
    # blanket exemption there would let a new section file join the paper unwatched -- the
    # precise failure this coverage check exists to end. The four non-section files are named
    # one at a time so that a fifth has to be triaged by whoever adds it.
    ("paper/CITATION_KEYS.md", "a citation-key index"),
    ("paper/GLOSSARY.md", "term definitions"),
    ("paper/REFERENCES_PAPER.json", "the manuscript bibliography"),
    ("paper/TERMINOLOGY_RULINGS.json", "adjudications on wording; each quotes the superseded "
                                       "sentence it rules on, including 22 count claims that "
                                       "a scan reads as stale and that are the record"),
    # --- root files that state no slate count.
    ("LICENSE", "a licence"),
    ("NOTICE", "third-party attribution"),
    ("VERSION", "a version string"),
    (".gitignore", "a gitignore"),
    ("styles.css", "stylesheet"),
    ("release.sh", "the release script"),
    ("requirements*.txt", "pinned dependencies"),
    ("skills-lock.json", "a tool manifest"),
    ("*.bib", "bibliographies"),
)

#: Never walked at all: not source, and large enough that walking them costs real time.
COVERAGE_SKIP_DIRS = {".git", ".venv", ".venv312", ".venvdockq", "__pycache__",
                      "node_modules"}
#: Not text. A count cannot be typed into these by hand in a form any scan could read.
COVERAGE_BINARY = {".png", ".jpg", ".jpeg", ".gif", ".pdf", ".docx", ".pptx", ".xlsx",
                   ".cif", ".npz", ".sqlite3", ".lock", ".zip", ".ico", ".woff", ".woff2"}


def _matches(rel: str, pattern: str) -> bool:
    """`fnmatch`, plus `dir/*` meaning the whole subtree rather than one level.

    `fnmatch`'s `*` crosses `/`, which is usually wrong and is exactly right here: an
    exemption for `runs/*` must cover `runs/2026-08-19T.../fold/log.txt` without anyone
    counting the levels.

    The consequence, stated because it is easy to misread the table above: these patterns are
    WIDER than they look. `data/*.json` covers `data/pae/x.json` too, and the `data/*/*`
    entries beside it are therefore redundant rather than load-bearing -- they are kept only
    because they name what lives there. Nothing here narrows; an exemption entry can only
    ever exempt more than its shape suggests, so a pattern must be written to be as specific
    as the reason it carries. That is why `paper/` is enumerated file by file.
    """
    return fnmatch.fnmatch(rel, pattern)


def coverage(watched: set[str]) -> tuple[list[str], list[tuple[str, str]]]:
    """Every text file in the tree, classified. Returns (unclassified, [(rel, reason)]).

    This is the derived half. It does not read a single count -- it asks only whether
    somebody has decided about each file, which is the question that has no false positives.
    """
    unclassified: list[str] = []
    exempt: list[tuple[str, str]] = []
    for path in sorted(REPO.rglob("*")):
        # Symlinks are followed, not skipped. `platform/tools/mutation_suite.py` builds its
        # scratch trees as real directories full of symlinks back to the repository, and
        # skipping them made this check see 54 files instead of 2,367 under `--root` -- so
        # the mutation that proves it would have been proving a vacuous version of it.
        if not path.is_file():
            continue
        rel_path = path.relative_to(REPO)
        if any(part in COVERAGE_SKIP_DIRS for part in rel_path.parts):
            continue
        if path.suffix.lower() in COVERAGE_BINARY or path.name == ".DS_Store":
            continue
        rel = str(rel_path)
        if rel in watched:
            continue
        for pattern, why in UNWATCHED:
            if _matches(rel, pattern):
                exempt.append((rel, why))
                break
        else:
            unclassified.append(rel)
    return unclassified, exempt


def restricted_for(rel: str) -> frozenset[str] | None:
    """The key set bound on this surface, or None to bind every key.

    Exact path first, then the glob entries, so a specific file can narrow a family.
    """
    if rel in RESTRICTED:
        return RESTRICTED[rel]
    for pattern, keys in RESTRICTED.items():
        if "*" in pattern and fnmatch.fnmatch(rel, pattern):
            return keys
    return None
SURFACE_GLOBS: tuple[str, ...] = (
    # The generators, because a sentence typed into one of them is a sentence on every
    # artefact it builds. "Not one study in this slate is confirmatory" was hand-written in
    # three document generators as well as in app.js, and the files they produced were never
    # tracked -- so scanning built output would scan nothing in a fresh clone, while scanning
    # the source caught the sentence before it was rendered four times. Those three
    # generators are no longer published, and this glob now covers the artefact builders that
    # remain; the reasoning is unchanged and is why the glob is a glob. Restricted below to
    # the keys a generator states about the slate as a whole; the per-study counts it
    # interpolates are values, not literals, and the ones it writes in prose belong to one
    # study.
    "platform/build_*.py",
    "docs/RELEASE_NOTES_*.md",
    "paper/PROJECT_FACTS.md",
    "paper/sec_*.md",
    # The deck copy is prose too, wearing a .json extension. It carried the same stale slate
    # sentence as the drafted sections -- "Eight studies, twenty-five hypotheses" and a slide
    # stamp reading "8 studies · 25 hypotheses" -- and it fanned out through a slide renderer
    # into two .pptx files and their PDFs, which is one more surface than the manuscript has.
    # Scanning the source rather than the slides is the point: a count fixed in a built deck
    # is fixed until the next rebuild. Like the rest of paper/, this glob matches nothing in
    # a clone and is here for the author's working tree.
    "paper/deck_copy*.json",
)

EXEMPT_TOKEN = "SLATE-COUNT-HISTORICAL"

WORD_TO_INT = {
    "one": 1, "two": 2, "three": 3, "four": 4, "five": 5, "six": 6, "seven": 7,
    "eight": 8, "nine": 9, "ten": 10, "eleven": 11, "twelve": 12, "thirteen": 13,
    "fourteen": 14, "fifteen": 15, "sixteen": 16, "seventeen": 17, "eighteen": 18,
    "nineteen": 19, "twenty": 20, "thirty": 30, "forty": 40,
}
#: Compounds matter more than they look: without "twenty-five" in the table the alternation
#: matches the "five" inside it and reports the manuscript's hypothesis count as 5.
for _tens, _base in (("twenty", 20), ("thirty", 30)):
    for _unit, _n in (("one", 1), ("two", 2), ("three", 3), ("four", 4), ("five", 5),
                      ("six", 6), ("seven", 7), ("eight", 8), ("nine", 9)):
        WORD_TO_INT[f"{_tens}-{_unit}"] = _base + _n

#: A numeral or a number-word, tolerating the markdown emphasis that wraps half of them.
#: Longest alternative first, so "twenty-five" wins over "five". The boundaries are the other
#: half of that lesson: without them, `\d{1,3}` matches the "1" of "H1 falsified" and the
#: "002" of a citation key, and every literature year in the manuscript becomes a slate count.
_WORDS = "|".join(sorted(WORD_TO_INT, key=len, reverse=True))
_NUMBODY = _WORDS + r"|\d{1,3}"
NUM = r"(?<![\w\-.])\*{0,2}(" + _NUMBODY + r")\*{0,2}(?![\w\-])"
#: The same thing without the capture. `record()` reads `m.group(1)`, so a pattern that names
#: two numbers must anonymise the one it is not binding -- otherwise "9 studies, 28
#: hypotheses" reports the hypothesis count as 9. Python's `re` has no variable-width
#: lookbehind, so this is the only way to require a neighbouring number without capturing it.
NUM_ANON = r"(?<![\w\-.])\*{0,2}(?:" + _NUMBODY + r")\*{0,2}(?![\w\-])"


def _n(raw: str) -> int:
    raw = raw.strip("*")
    return int(raw) if raw.isdigit() else WORD_TO_INT[raw.lower()]


#: (key into the expected table, compiled pattern, what the sentence is claiming).
#:
#: Each pattern binds a number to the label immediately beside it. The filler between the two
#: is spelled out rather than left as a wildcard: a loose `(NUM).{0,30}studies` matches "the
#: two screening studies" in a sentence about retained versions and reports the slate as 2.
RULES: list[tuple[str, re.Pattern[str], str]] = [
    ("studies", re.compile(NUM + r"\s+pre-?registered\s+stud(?:y|ies)\b", re.I),
     "the number of pre-registered studies"),
    ("studies", re.compile(NUM + r"\s+stud(?:y|ies)\s+(?:were\s+|was\s+)?"
                                 r"(?:pre-?registered|registered)\b", re.I),
     "the number of pre-registered studies"),
    ("studies", re.compile(r"(?:slate|protocol)\s+of\s+" + NUM + r"\s+studies\b", re.I),
     "the number of studies in the slate"),
    ("studies", re.compile(r"artefacts\s+of\s+" + NUM + r"\s+studies\b", re.I),
     "the number of studies whose artefacts ship"),
    ("studies", re.compile(NUM + r"\s+studies\s+in\s+(?:this|the)\s+slate\b", re.I),
     "the number of studies in the slate"),
    # The lookahead carries both spellings of the same false positive: "25 hypotheses decided
    # by a test statistic" and "7 hypotheses were decided by a test statistic" are claims
    # about the decision-kind split, not about the size of the slate, and the rule below
    # binds them. Without the `were`, the second reads as a slate total of 7.
    ("hypotheses", re.compile(NUM + r"\s+hypotheses\b(?!\s+(?:were\s+)?decided\b)", re.I),
     "the number of registered hypotheses"),
    ("decided_by_a_test", re.compile(NUM + r"\s+(?:hypotheses\s+)?(?:were\s+)?"
                                           r"decided\s+by\s+a\s+test\s+statistic", re.I),
     "the number of hypotheses decided by a test statistic"),
    ("decided_by_a_threshold", re.compile(NUM + r"\s+(?:hypotheses\s+)?(?:were\s+)?"
                                                r"(?:decided\s+)?by\s+a\s+(?:pre-?fixed\s+|"
                                                r"fixed\s+|pre-?specified\s+)?threshold", re.I),
     "the number of hypotheses decided by a threshold"),
    ("confirmed", re.compile(NUM + r"\s+(?:were\s+|of\s+which\s+)?confirmed\b", re.I),
     "the number of confirmed hypotheses"),
    ("falsified", re.compile(NUM + r"\s+(?:were\s+)?falsified\b", re.I),
     "the number of falsified hypotheses"),
    # The noun form, under its own key so that README can bind it. "including the eleven
    # falsifications" stood in README's How-to-cite block two falsifications out of date,
    # and nothing here could see it: the adjective rule needs "N falsified", and README is
    # restricted below because "Slate #12 falsified it" would otherwise read as a slate
    # total. The noun has no such collision -- no study is numbered "falsifications" -- so
    # it binds where the adjective cannot, on the paragraph that tells a citer what this
    # project established.
    ("falsifications", re.compile(NUM + r"\s+falsifications\b", re.I),
     "the number of falsified hypotheses, stated as a noun"),
    ("not_tested", re.compile(NUM + r"\s+not\s+tested\b", re.I),
     "the number of hypotheses left untested"),
    # ------------------------------------------------------------------------------------
    # THE NOMINALISED HALF OF THE VERDICT VOCABULARY.
    #
    # `falsifications` above was added one key at a time, after a reader found the stale
    # form. That is the wrong order, and it is the same order that produced the surface list
    # this guard was born from: fix what was reported, leave the identical hole beside it.
    # The rules below close the rest of the nominalisations in one pass, whether or not a
    # reader has yet walked into one.
    #
    # A count stated as a participle ("13 falsified") and the same count stated as a noun
    # ("the thirteen falsifications") are the same claim, and every pattern here bound only
    # the participle. Every key whose label is a participle or an adjective now carries its
    # noun form; the keys whose labels are already nouns -- `hypotheses`, `plans`, `suites`,
    # `retained_versions`, `screened_constructs`, `distinct_peptides` -- need nothing, and
    # saying so here is what stops the next pass from re-asking.
    #
    # ONE nominalisation is deliberately NOT added, and the reason is the reason the
    # restriction table exists: `deviations`. "N deviations" is a real phrasing in this
    # repository, and it is a PER-STUDY count wherever it appears -- README.md's Slate #10
    # paragraph says "The protocol audit reports two deviations", docs/RELEASE_NOTES_v1.1.0.md
    # says "records 0 deviations" of study #12. The slate-wide total (18 today) is bound by
    # the WORDED denial and by nothing else, on purpose. A rule that cannot tell one study's
    # ledger from the slate's would report both of those correct sentences as stale, and a
    # guard that cries wolf on correct prose is worth less than no guard.
    ("confirmations", re.compile(NUM + r"\s+confirmations\b", re.I),
     "the number of confirmed hypotheses, stated as a noun"),
    ("not_tested", re.compile(NUM + r"\s+(?:hypotheses\s+)?(?:left\s+)?untested\b", re.I),
     "the number of untested hypotheses, stated as an attribute"),
    ("studies", re.compile(NUM + r"\s+pre-?registrations\b", re.I),
     "the number of pre-registered studies, stated as a noun"),
    ("decided_by_a_test",
     re.compile(NUM + r"\s+test[-\s]statistic\s+decisions\b", re.I),
     "the number of hypotheses decided by a test statistic, stated as a noun"),
    ("decided_by_a_threshold",
     re.compile(NUM + r"\s+threshold\s+decisions\b", re.I),
     "the number of hypotheses decided by a threshold, stated as a noun"),
    # ------------------------------------------------------------------------------------
    # THE ROSTER LINE, and the split beside it.
    #
    # README.md line 90 -- the first quantitative sentence a visitor reads -- says
    # "9 pre-registered studies, 28 hypotheses of which 27 are decided". `studies` was bound
    # there; the other two numbers were not, because the loose `hypotheses` rule is excluded
    # on README (three real sentences in that file count ONE study's three hypotheses).
    #
    # These two forms cannot be per-study claims. A sentence that names a hypothesis count in
    # the same breath as a study count is describing the slate by construction, and "of which
    # N are decided" is a split of that same total. So they get their own keys and are bound
    # on README, exactly as `falsifications` is bound where `falsified` cannot be.
    ("hypotheses_in_roster",
     re.compile(NUM_ANON + r"\s+(?:pre-?registered\s+)?studies,\s+" + NUM
                + r"\s+hypotheses\b", re.I),
     "the hypothesis count stated beside the study count"),
    ("studies",
     re.compile(NUM + r"\s+(?:pre-?registered\s+)?studies,\s+" + NUM_ANON
                + r"\s+hypotheses\b", re.I),
     "the study count stated beside the hypothesis count"),
    # `(?!\s+by)` is what separates this from the two decision-kind rules: "7 were decided by
    # a test statistic" is a kind, "27 are decided" is the total. Without it this rule reads
    # every kind sentence as the total and reports the slate as 7.
    ("decided", re.compile(NUM + r"\s+(?:are\s+|were\s+)decided\b(?!\s+by\b)", re.I),
     "the number of hypotheses that reached a verdict"),
    ("plans", re.compile(NUM + r"\s+(?:registered\s+)?(?:analysis\s+)?plans\b", re.I),
     "the number of registered analysis plans"),
    ("suites", re.compile(NUM + r"\s+(?:verification\s+|test\s+)?suites\b", re.I),
     "the number of verification suites verify_all.py runs"),
    # The two shields.io badges at the top of README.md. They need their own patterns because
    # a badge writes the count as `8_suites_passing`, and NUM's trailing boundary refuses a
    # digit followed by a word character -- correctly, or every citation key becomes a count.
    # These are the first two numbers a visitor sees about this project and nothing bound
    # them until now.
    ("suites", re.compile(r"verification-(\d{1,3})_suites_passing", re.I),
     "the suite count in the README verification badge"),
    ("studies", re.compile(r"pre--registered_studies-(\d{1,3})\b", re.I),
     "the study count in the README badge"),
    ("retained_versions", re.compile(NUM + r"\s+retained\s+versions\b", re.I),
     "the number of retained versions of the two screening studies"),
    ("studies_confirmatory", re.compile(NUM + r"\s+confirmatory\s+stud(?:y|ies)\b", re.I),
     "the number of studies whose audit records confirmatory = true"),
    # The complement of the line above, and the sentence that replaced the manuscript's
    # denial that a deviation ledger exists. It is bound rather than left as prose because a
    # denial and a wrong count fail the same way: both describe a slate that is not this one.
    # The running TOTAL of deviations is deliberately not stated in the manuscript and not
    # bound here -- it moves whenever any study's audit is regenerated. It lives in
    # paper/PROJECT_FACTS.md instead, inside the block platform/build_project_facts.py owns.
    ("studies_with_a_deviation",
     re.compile(NUM + r"\s+of\s+the\s+\d{1,3}\s+studies\s+deviate\b", re.I),
     "the number of studies that deviated from their registered plan"),
    ("studies_with_a_deviation",
     re.compile(r"연구\s*가운데\s*(\d{1,3})개가\s*적어도\s*한\s*가지\s*점에서\s*이탈"),
     "the number of studies that deviated from plan, in the Korean edition"),
    ("screened_constructs",
     re.compile(NUM + r"\s+candidate[-\u2013\u2014]receptor\s+constructs\b", re.I),
     "the number of candidate-receptor constructs the screens fold"),
    # One intervening adjective is allowed, because the manuscript writes "twelve distinct
    # chimeric peptides". Two would start matching sentences about something else.
    ("distinct_peptides",
     re.compile(NUM + r"\s+distinct\s+(?:\w+\s+)?peptides\b", re.I),
     "the number of DISTINCT peptides those constructs cover"),
    # The claim this rule exists for. "all 13 distinct candidates" stood on README.md,
    # CITATION.cff, .zenodo.json, docs/REGISTRATION.md and the release note; 13 is the
    # construct count, and it is 12 molecules that are distinct.
    ("distinct_peptides",
     re.compile(NUM + r"\s+distinct\s+(?:candidates|designs)\b", re.I),
     "the number of distinct designed molecules screened"),
]

#: Claims that state a count in words rather than as a number. "Not one study is confirmatory"
#: was written when it was true of all eight studies; #12's audit records confirmatory = true
#: with an empty deviation list, so the sentence now erases the one study that cleared its plan.
WORDED: list[tuple[str, int, re.Pattern[str], str]] = [
    # The pattern was `not one study is confirmatory` and nothing else, so it matched the
    # release note and missed every other copy: app.js said "Not one study IN THIS SLATE is
    # confirmatory", a deck generator said "in the slate", a report generator's section 3.2
    # said "not one study in this slate is confirmatory". Four words of filler was the whole
    # difference between a guard that fires and a guard that does not, which is why the
    # slate/of-the-N wrappers are spelled out here rather than left to an exact phrase.
    ("studies_confirmatory", 0,
     re.compile(r"not\s+one\s+(?:of\s+the\s+" + NUM + r"\s+)?stud(?:y|ies)\s+"
                r"(?:in\s+(?:this|the)\s+slate\s+)?(?:is|are)\s+confirmatory", re.I),
     "asserts that no study is confirmatory"),
    # Present tense only, and deliberately. "v1.0.0's note said no study WAS confirmatory.
    # That was true when it was written and is not true now" is a sentence in
    # docs/RELEASE_NOTES_v1.1.0.md that reports a superseded claim and retracts it in the
    # same breath -- and it is generated by build_release_notes.py from the counts, so no
    # number in that file's output path is typed and none can go stale. Binding the past
    # tense here would make the guard fire on a correct retraction that it cannot be given
    # an exemption marker for: the note is hard-wrapped after interpolation, so the sentence
    # and a marker cannot be held on one line, and `exempt` is a per-line test.
    ("studies_confirmatory", 0,
     re.compile(r"(?:no|neither)\s+stud(?:y|ies)\s+(?:in\s+(?:this|the)\s+slate\s+)?"
                r"(?:is|are)\s+confirmatory", re.I),
     "asserts that no study is confirmatory"),
    # The same denial in the Korean edition, which the number-parity check cannot see for the
    # same reason it could not see the deviation-ledger denial: a sentence with no numeral in
    # it reads identically in both editions whether it is true or false.
    ("studies_confirmatory", 0,
     re.compile(r"(?:어느|어떤)\s*연구도\s*확증적이지\s*않"),
     "asserts in the Korean edition that no study is confirmatory"),
    # A denial is a count of zero, and it went unseen for the same reason "Eight" did: no
    # numeral. `paper/sec_discussion_3_limits.md` said "no ledger of such departures is
    # compiled here, and none is claimed" while every study artefact carried a
    # machine-generated `analysis.prespec_audit.deviations` list -- 17 departures across the
    # slate, rendered on the page under "Protocol audit: deviations". The most checkable
    # virtue the project has was disclaimed in its own Limitations section. Bound to the
    # artefacts: the claim implies 0 and `deviations` is recounted from data/ at run time.
    ("deviations", 0,
     re.compile(r"no\s+ledger\s+of\s+(?:such\s+|these\s+|those\s+)?departures?\s+"
                r"is\s+compiled", re.I),
     "asserts that no ledger of protocol departures is compiled"),
    # The same denial in Korean. A number-parity check between editions could not see this
    # one either: a sentence that states no number is identical in both editions whether it
    # is true or false, so the English correction does not drag the Korean along behind it.
    ("deviations", 0,
     re.compile(r"이탈의\s*목록은\s*여기서\s*작성되지\s*않았"),
     "asserts in the Korean edition that no ledger of protocol departures is compiled"),
]


def deviations_recorded() -> int:
    """Recount the deviation ledger from the study artefacts, not from a summary of them.

    `analysis.prespec_audit.deviations` is machine-generated per study. Counting it here
    rather than reading a total out of `slate.json` means the WORDED denial below is refuted
    by the same records a reader would open to check it.
    """
    total, seen = 0, set()
    for f in sorted((REPO / "data").glob("study_*.json")):
        body = json.loads(f.read_text())
        a = body.get("analysis") or body
        if not a.get("verdicts"):
            continue      # an input artefact with no decisions is not a study of the slate
        sid = a.get("study_id")
        if sid in seen:
            raise SystemExit(f"two artefacts claim study_id {sid}; refusing to guess")
        seen.add(sid)
        total += len((a.get("prespec_audit") or {}).get("deviations") or [])
    return total


def screen_population() -> tuple[int, int]:
    """Constructs and distinct peptides, from the two screens, which must agree.

    Both studies fold the same candidate set, so a disagreement means one was re-analysed and
    the other was not -- the stale-base failure this guard exists for, one level down.
    Refusing is better than picking a side.
    """
    seen = set()
    for name in ("study_candidate_screen.json", "study_msa_specificity.json"):
        a = json.loads((REPO / "data" / name).read_text())["analysis"]
        mult = a.get("peptide_multiplicity")
        if not mult:
            raise SystemExit(
                f"data/{name} carries no analysis.peptide_multiplicity: re-run that study "
                "with --analyse. Without it there is nothing to bind a candidate count to.")
        seen.add((mult["n_constructs"], mult["n_distinct_peptides"]))
    if len(seen) != 1:
        raise SystemExit(f"the two screens disagree about the population: {sorted(seen)}")
    return seen.pop()


def expected() -> dict[str, int]:
    """Every value read from the artefacts, none of them typed here."""
    slate = json.loads((REPO / "data" / "slate.json").read_text())
    counts = slate["counts"]
    sep = slate["separation_across_versions"]
    n_versions = sep.get("n_versions")
    if n_versions != len(sep.get("versions") or []):
        raise SystemExit("slate.json disagrees with itself about separation_across_versions")

    sys.path.insert(0, str(REPO))
    import importlib.util
    spec = importlib.util.spec_from_file_location("_verify_all", REPO / "verify_all.py")
    va = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(va)

    n_constructs, n_distinct = screen_population()

    # The decided total is derivable two ways from the same block, and they must agree.
    # A guard that reads one of them cannot tell a mis-split from a moved slate; requiring
    # both means a hypothesis that changed kind without changing verdict, or the reverse,
    # stops this guard rather than being averaged over.
    decided_by_kind = counts["decided_by_a_test"] + counts["decided_by_a_threshold"]
    decided_by_verdict = counts["hypotheses"] - counts["not_tested"]
    if decided_by_kind != decided_by_verdict:
        raise SystemExit(
            f"data/slate.json disagrees with itself about how many hypotheses are decided: "
            f"{decided_by_kind} by decision kind, {decided_by_verdict} by verdict. "
            "Re-run platform/build_slate.py; do not pick one.")

    return {
        "studies": counts["studies"],
        "hypotheses": counts["hypotheses"],
        "hypotheses_in_roster": counts["hypotheses"],
        "decided": decided_by_kind,
        "confirmed": counts["confirmed"],
        "confirmations": counts["confirmed"],
        "falsified": counts["falsified"],
        "falsifications": counts["falsified"],
        "not_tested": counts["not_tested"],
        "studies_confirmatory": counts["studies_confirmatory"],
        "decided_by_a_test": counts["decided_by_a_test"],
        "decided_by_a_threshold": counts["decided_by_a_threshold"],
        "deviations": deviations_recorded(),
        "studies_with_a_deviation": counts["studies"] - counts["studies_confirmatory"],
        "plans": len(list((REPO / "prespec").glob("*.json"))),
        "suites": len(va.SUITES),
        "retained_versions": n_versions,
        "screened_constructs": n_constructs,
        "distinct_peptides": n_distinct,
    }


def surfaces() -> list[Path]:
    found = [REPO / s for s in SURFACES]
    for pattern in SURFACE_GLOBS:
        head, _, tail = pattern.partition("/")
        found += sorted((REPO / head).glob(tail))
    return [p for p in found if p.is_file()]


def scan(want: dict[str, int]) -> tuple[list[tuple], int]:
    r"""Match over the whole file, not line by line.

    These are hard-wrapped markdown files, and the count and its label land on either side of
    a newline often enough that a line-based scan reads "5 hypotheses" as the slate total when
    the sentence continues "decided by a test statistic". Every pattern here uses `\s+`, which
    spans the wrap; the line number is recovered from the match offset.
    """
    hits: list[tuple] = []
    checked = 0
    for path in surfaces():
        rel = str(path.relative_to(REPO))
        text = path.read_text(errors="replace")

        def line_of(pos: int) -> int:
            return text.count("\n", 0, pos) + 1

        def exempt(m: re.Match[str]) -> bool:
            a = text.rfind("\n", 0, m.start()) + 1
            b = text.find("\n", m.end())
            return EXEMPT_TOKEN in text[a: b if b != -1 else len(text)]

        def record(m: re.Match[str], key: str, got: int, claim: str) -> None:
            nonlocal checked
            checked += 1
            if got != want[key]:
                src = " ".join(m.group(0).split())
                hits.append((rel, line_of(m.start()), claim, got, want[key], src))

        allowed = restricted_for(rel)
        for key, pat, claim in RULES:
            if allowed is not None and key not in allowed:
                continue
            for m in pat.finditer(text):
                if not exempt(m):
                    record(m, key, _n(m.group(1)), claim)
        for key, implied, pat, claim in WORDED:
            if allowed is not None and key not in allowed:
                continue
            for m in pat.finditer(text):
                if not exempt(m):
                    record(m, key, implied, claim)
    return hits, checked


#: (text, key, value the scan must read out of it). A guard that cannot be shown to fire is
#: indistinguishable from one that passes vacuously -- which is how the eight-study sentence
#: survived a repository with 448 checks in it. `--self-test` runs these before the scan.
SELF_TEST: tuple[tuple[str, str, int], ...] = (
    ("Eight studies were pre-registered under content hashes", "studies", 8),
    ("**8 pre-registered studies**, 25 hypotheses", "studies", 8),
    ("reports nine studies pre-registered under content hashes", "studies", 9),
    ("the artefacts of 9 studies", "studies", 9),
    ("27 registered analysis plans", "plans", 27),
    ("26 registered analysis plans and 313 automated checks", "plans", 26),
    ("across six suites, each verified to fail", "suites", 6),
    ("8 verification suites in which every check", "suites", 8),
    ("of which 13 were confirmed", "confirmed", 13),
    ("thirteen confirmed, eleven falsified, one not tested", "falsified", 11),
    # The sentence the noun rule exists for, in the form it went stale in and in the form
    # that replaced it.
    ("carries every verdict, including the eleven falsifications", "falsifications", 11),
    ("every verdict, including the 13 falsifications", "falsifications", 13),
    ("twenty-five hypotheses: thirteen confirmed", "hypotheses", 25),
    ("falsified in all eleven retained versions", "retained_versions", 11),
    ("5 hypotheses\ndecided by a test statistic", "decided_by_a_test", 5),
    ("7 hypotheses were decided by a test statistic", "decided_by_a_test", 7),
    ("19 by a pre-fixed threshold", "decided_by_a_threshold", 19),
    ("8 of the 9 studies deviate in at least one respect", "studies_with_a_deviation", 8),
    ("9개 연구 가운데 8개가 적어도 한 가지 점에서 이탈하였고",
     "studies_with_a_deviation", 8),
    # The three keys below had no case here until platform/tools/mutation_suite.py enumerated
    # the rule table and reported them UNCOVERED. Each is a key the guard binds on live
    # surfaces, so "no case" meant the pattern was trusted rather than shown to fire.
    ("of which 14 were confirmed, 13 falsified and 1 not tested", "not_tested", 1),
    ("a screen of 13 candidate-receptor constructs", "screened_constructs", 13),
    ("13 candidate\u2013receptor constructs covering 12 distinct peptides",
     "screened_constructs", 13),
    ("13 candidate\u2013receptor constructs covering 12 distinct peptides",
     "distinct_peptides", 12),
    # The sentence the distinct-peptide rule exists for: it stood on five surfaces, and 13 is
    # the number of CONSTRUCTS. One 41-mer is screened against two receptors.
    ("all 13 distinct candidates", "distinct_peptides", 13),
    ("twelve distinct chimeric peptides", "distinct_peptides", 12),
    ("[![Verification](https://img.shields.io/badge/verification-8_suites_passing-brightgreen"
     "?style=flat-square)](verify_all.py)", "suites", 8),
    ("[![Studies](https://img.shields.io/badge/pre--registered_studies-9-blueviolet)]",
     "studies", 9),
    # The nominalised half. Each pair is the stale form and the current one, because a rule
    # that only ever sees the right answer has not been shown to read the number at all.
    ("every verdict, including the fourteen confirmations", "confirmations", 14),
    ("11 confirmations, 13 falsifications", "confirmations", 11),
    ("11 confirmations, 13 falsifications", "falsifications", 13),
    ("thirteen confirmed, eleven falsified, one untested", "not_tested", 1),
    ("28 hypotheses, 2 left untested", "not_tested", 2),
    ("nine pre-registrations under content hashes", "studies", 9),
    ("eight pre-registrations under content hashes", "studies", 8),
    ("7 test-statistic decisions and 20 threshold decisions", "decided_by_a_test", 7),
    ("7 test-statistic decisions and 20 threshold decisions",
     "decided_by_a_threshold", 20),
    ("5 test statistic decisions", "decided_by_a_test", 5),
    # The roster line, in the form it stands in README.md today and in the form it stood in
    # paper/deck_copy.json while the slate had moved out from under it.
    ("9 pre-registered studies, 28 hypotheses of which 27 are decided",
     "hypotheses_in_roster", 28),
    ("9 pre-registered studies, 28 hypotheses of which 27 are decided", "studies", 9),
    ("9 pre-registered studies, 28 hypotheses of which 27 are decided", "decided", 27),
    ("Eight studies, twenty-five hypotheses", "hypotheses_in_roster", 25),
    ("Eight studies, twenty-five hypotheses", "studies", 8),
    ("of which 26 are decided", "decided", 26),
)

#: (surface, text, key that must NOT be bound there). The restriction is only worth having if
#: it is shown to hold: each of these is a real sentence in README.md that a slate-wide scan
#: reads as a stale total.
SELF_TEST_RESTRICTED: tuple[tuple[str, str, str], ...] = (
    ("README.md", "round-2 re-classified all three hypotheses as threshold criteria",
     "hypotheses"),
    ("README.md", "**All three hypotheses confirmed.**", "hypotheses"),
    ("README.md", "Slate #12 falsified it and that clause is retracted.", "falsified"),
    # The noun is bound on README, so it must be shown to stay silent on the same sentence:
    # binding it would be worth nothing if it traded one false reading for another.
    ("README.md", "Slate #12 falsified it and that clause is retracted.", "falsifications"),
    ("README.md", "across the screen's six retained versions it ran -0.006",
     "retained_versions"),
    ("README.md", "that run reported nine distinct designs, and the current v8",
     "distinct_peptides"),
    # app.js, and the reason `falsifications` is bound on README but not here: the noun is
    # not immune to a per-study reading, it merely has none on README. This sentence is real,
    # it is correct, and binding the noun on app.js would report it as a stale slate total.
    ("app.js", "a reader who stopped there came away believing those were the only two "
               "falsifications in the slate", "falsifications"),
)

#: Denials, which state a count of zero in words. Each entry is (text, key, implied value).
SELF_TEST_WORDED: tuple[tuple[str, str, int], ...] = (
    ("no ledger of such departures is compiled here, and none is claimed", "deviations", 0),
    ("그러한 이탈의 목록은 여기서 작성되지 않았고, 작성했다고 주장하지도 않는다",
     "deviations", 0),
    ("Not one study is confirmatory", "studies_confirmatory", 0),
    # The three shipped variants that the exact-phrase pattern missed. app.js printed the
    # first in bold on the Slate tab; a deck generator printed the second and a report
    # generator's section 3.2 the third -- all three above or beside a derived paragraph
    # that named #12 as the exception. The two generators are no longer published; the
    # variants stay here because a pattern narrowed to one phrasing is the defect.
    ("Not one study in this slate is confirmatory", "studies_confirmatory", 0),
    ("Not one study in the slate is confirmatory", "studies_confirmatory", 0),
    ("not one study in this slate is confirmatory", "studies_confirmatory", 0),
    # The zero-branch of build_slate.py's own generated headline, so the guard still reads
    # the sentence the generator would write if the count went back to zero.
    ("Not one of the 9 studies in this slate is confirmatory.", "studies_confirmatory", 0),
    ("no study is confirmatory", "studies_confirmatory", 0),
    ("이 슬레이트의 어느 연구도 확증적이지 않다", "studies_confirmatory", 0),
)

#: Strings that must match NOTHING. Every one of these was a false positive during
#: development, and each names a way a slate-count scan goes wrong: a hypothesis label read as
#: a numeral, a citation year, a literature claim about other people's studies, a compound
#: number word cut in half, and a count of something else that happens to share the noun.
SELF_TEST_SILENT: tuple[str, ...] = (
    "H1 falsified in all 11 retained versions",          # "H1 falsified" is not a count
    "replicated independently [@guerreiro2013] and confirmed",   # citation year
    "of 27 studies carrying the Preregistered badge, two deviated",  # someone else's studies
    # The past-tense retraction in docs/RELEASE_NOTES_v1.1.0.md, which reports what v1.0.0's
    # note said and withdraws it in the next clause. It must stay silent, or the guard fires
    # on a file whose every count is generated.
    "v1.0.0's note said no study was confirmatory. That was true when it was written",
    "falsified in all eleven retained versions of the two screening studies",  # 2 != slate
    "it covers data/corpus_ACHE.json, three study artefacts, and 17 runs",  # ChEMBL licence
)

#: Strings where ONE key must stay silent while others legitimately fire. A decision-kind
#: sentence names a number next to the word "hypotheses" and is not a slate total; the
#: `decided_by_a_test` rule must read it and the `hypotheses` rule must not.
SELF_TEST_NOT: tuple[tuple[str, str], ...] = (
    ("7 hypotheses were decided by a test statistic", "hypotheses"),
    ("25 hypotheses decided by a test statistic", "hypotheses"),
    ("H1 falsified in all 11 retained versions", "falsified"),
    # The decided TOTAL must not read a decision KIND. Without the `(?!\s+by)` lookahead
    # this rule reports the slate's decided count as 7.
    ("7 were decided by a test statistic", "decided"),
    ("20 were decided by a pre-fixed threshold", "decided"),
    # ...and the roster rule must not read a hypothesis count that stands alone, or it
    # duplicates the loose rule on every surface and re-imports the collision the split
    # exists to avoid.
    ("28 hypotheses of which 27 are decided", "hypotheses_in_roster"),
)


def _read(text: str) -> list[tuple[str, int]]:
    return [(k, _n(m.group(1))) for k, pat, _ in RULES for m in pat.finditer(text)]


def _read_worded(text: str) -> list[tuple[str, int]]:
    return [(k, implied) for k, implied, pat, _ in WORDED if pat.search(text)]


def self_test() -> int:
    """Assert the patterns fire where they must and stay silent where they must."""
    failures = 0
    for text, key, value in SELF_TEST:
        got = _read(text)
        if (key, value) not in got:
            print(f"  MISS  {text!r}\n        expected {key}={value}, read {got}")
            failures += 1
    for text, key, value in SELF_TEST_WORDED:
        got = _read_worded(text)
        if (key, value) not in got:
            print(f"  MISS (worded)  {text!r}\n        expected {key}={value}, read {got}")
            failures += 1
    for text in SELF_TEST_SILENT:
        # The worded patterns are read here too. They were not, and that is half the reason
        # the confirmatory denial was never shown to have a false-positive boundary: the
        # silent cases exercised the numeric rules only, so a worded pattern could be
        # widened without anything checking what it started matching.
        got = _read(text) + _read_worded(text)
        # The last case legitimately reports the retained-version count; only a *slate* claim
        # is a false positive there.
        got = [g for g in got if g != ("retained_versions", 11)]
        if got:
            print(f"  FALSE POSITIVE  {text!r}\n        read {got}")
            failures += 1
    for text, forbidden in SELF_TEST_NOT:
        got = [g for g in _read(text) if g[0] == forbidden]
        if got:
            print(f"  FALSE POSITIVE  {text!r}\n        read {got}, and {forbidden} must "
                  "stay silent here")
            failures += 1
    for rel, text, forbidden in SELF_TEST_RESTRICTED:
        allowed = restricted_for(rel)
        fires = [g for g in _read(text) if g[0] == forbidden]
        if allowed is None or (forbidden in allowed and fires):
            print(f"  RESTRICTION LOST  {rel}: {text!r}\n        {forbidden} is bound here "
                  f"and reads {fires}")
            failures += 1
    total = (len(SELF_TEST) + len(SELF_TEST_WORDED) + len(SELF_TEST_SILENT)
             + len(SELF_TEST_NOT) + len(SELF_TEST_RESTRICTED))
    print(f"self-test: {total - failures} passed, {failures} failed")
    return failures


def coverage_report() -> int:
    """`--coverage`: the exemption table, and how many count claims it is standing over.

    An exemption is a promise that a file states no slate count worth binding. That promise
    is checkable, and this is where it gets checked: every exempt file is scanned with the
    full rule table and the disagreements are counted PER PATTERN. A pattern standing over a
    large number is not necessarily wrong -- `reviews/*` stands over the audit transcripts
    that quote every stale sentence they report, and that is the reason it is exempt -- but
    the number is the thing that lets a reader argue with the entry instead of trusting it.

    This is advisory and exits 0 on its own. Turning it into a failure would mean triaging
    133 correct sentences, and a guard that demands that is a guard that gets deleted.
    """
    want = expected()
    watched = {str(p.relative_to(REPO)) for p in surfaces()}
    unclassified, exempt = coverage(watched)
    per_pattern: dict[str, list[tuple[str, str, int, int]]] = {}
    for rel, _why in exempt:
        path = REPO / rel
        try:
            text = path.read_text(errors="replace")
        except OSError:
            continue
        pattern = next(pat for pat, _w in UNWATCHED if _matches(rel, pat))
        for key, pat, claim in RULES:
            for m in pat.finditer(text):
                got = _n(m.group(1))
                if got != want[key]:
                    per_pattern.setdefault(pattern, []).append((rel, key, got, want[key]))

    print("=" * 78)
    print("coverage: every text file is a decision somebody made")
    print("=" * 78)
    print(f"\n{len(watched)} watched · {len(exempt)} exempt · {len(unclassified)} undecided\n")
    for pattern, why in UNWATCHED:
        n_files = sum(1 for rel, _w in exempt if _matches(rel, pattern)
                      and next(p for p, _ in UNWATCHED if _matches(rel, p)) == pattern)
        stale = per_pattern.get(pattern, [])
        flag = f"{len(stale):>4} claim(s) a scan would call stale" if stale else ""
        print(f"  {pattern:<32} {n_files:>5} file(s)  {flag}")
        print(f"      {why[:100]}")
    if unclassified:
        print("\nUNDECIDED:")
        for rel in unclassified:
            print(f"  {rel}")
        return 1
    print("\nAdvisory. The numbers above are the price of each exemption, stated so it can be")
    print("argued with. Nothing here fails a build.\n")
    return 0


def main() -> int:
    """`--root DIR` points every read at another tree.

    Not a convenience. `platform/tools/mutation_suite.py` plants a stale count in a scratch
    copy and requires this guard to fail on it; without a root it can be pointed at, the
    only way to prove that is to damage the repository and undo it afterwards, which is a
    proof nobody runs twice. Every path in this file goes through the module-level `REPO`,
    so rebinding it here rebinds all of them -- including `verify_all.SUITES`, which is read
    from the tree under test rather than from this one, so a mutation that adds a suite
    without correcting the surfaces that count them is caught too.
    """
    global REPO
    if "--root" in sys.argv:
        REPO = Path(sys.argv[sys.argv.index("--root") + 1]).resolve()
    if "--self-test" in sys.argv:
        return 1 if self_test() else 0
    if "--coverage" in sys.argv:
        return coverage_report()
    want = expected()
    hits, checked = scan(want)
    watched_paths = surfaces()
    files = len(watched_paths)
    watched = {str(p.relative_to(REPO)) for p in watched_paths}
    unclassified, exempt = coverage(watched)
    print("=" * 78)
    print("metadata count guard: hand-typed slate counts must equal the artefacts")
    print("=" * 78)
    print("\ncurrent values, read from data/slate.json, prespec/ and verify_all.SUITES:")
    for k in sorted(want):
        print(f"    {k:<22} {want[k]}")
    print(f"\n{checked} count claim(s) bound across {files} surface(s)")
    # The derived half. Printed on every run, because a coverage number that only appears
    # when it is bad is a number nobody has a baseline for.
    print(f"{len(watched) + len(exempt)} text file(s) classified: {len(watched)} watched, "
          f"{len(exempt)} exempted by name in UNWATCHED, {len(unclassified)} undecided")
    if unclassified:
        print("\nFAIL — text file(s) that are neither watched nor exempted:\n")
        for rel in unclassified:
            print(f"  {rel}")
        print("\nEvery text file in this tree must be a decision somebody made. Either add it")
        print("to SURFACES/SURFACE_GLOBS (with a RESTRICTED entry if only some keys apply),")
        print("or add it to UNWATCHED with the reason it states no slate count. This check is")
        print("here because app.js, index.html and verify_all.py each went stale on a surface")
        print("nobody had decided about.\n")
        return 1
    if not hits:
        print("\nPASS — every hand-typed slate count matches the artefact it summarises,")
        print("and every text file in the tree is either watched or exempted by name.\n")
        return 0
    print(f"\nFAIL — {len(hits)} stale count(s):\n")
    for rel, line, claim, got, exp, src in hits:
        print(f"  {rel}:{line}")
        print(f"    {claim}: states {got}, artefacts say {exp}")
        print(f"    | {src}")
    print("\nFix the surface, never the artefact. If the sentence is deliberately quoting a")
    print(f"superseded count, mark that line {EXEMPT_TOKEN} and say why in the text.\n")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
