#!/usr/bin/env python3
"""Guard: every version stamp must name the version it is actually about.

The defect this exists for
--------------------------
`VERSION` read `1.1.0`. Ten stamps across six files read `1.0.0`, and one of them read this:

    - type: doi
      value: 10.5281/zenodo.22032685
      description: Version DOI -- permanently fixed to v1.0.0 (this release)

So a cold reader arriving at the repository was told, by the file GitHub's *Cite this
repository* button reads, to cite **Version 1.0.0** and DOI `...22032685` -- while the
abstract three lines above it described nine studies, study #12, the +0.0895 aggregate and
the withdrawal of the per-candidate reading. Study #12 was registered 2026-08-22T06:43:11Z;
the deposit behind `...22032685` was made 2026-08-20. The citation instruction and the
content it sat beside were two days and one retraction apart.

Nothing bound them. `release.sh` line 41 checks that `VERSION` equals the version *typed on
the command line* and nothing else, so `./release.sh 1.1.0` would have passed every gate and
published a tag whose citable record said 1.0.0.

The distinction this guard is built on
--------------------------------------
A repository carries two kinds of version stamp and they must not be made to agree:

**IDENTITY** -- "what version is this tree?" `CITATION.cff: version`, `codemeta.json .version`,
`.zenodo.json .version`, `biotools.json .version[]`, the README's how-to-cite blocks, and the
citation block `platform/build_dataset.py` copies onto the Provenance tab. Every one of these
must equal `VERSION`.

**PINNED** -- "what is this already-published thing?" A Zenodo *version* DOI is frozen to the
bytes of one deposit forever. A `releases/tag/v1.0.0.tar.gz` URL can only name a tag that has
been pushed. These must name a version that is **published**, and relabelling them to follow
`VERSION` would make the repository assert something Zenodo and GitHub will never make true.

The naive repair -- rewrite every `1.0.0` to `1.1.0` -- fixes the first class and breaks the
second, which is why both halves are asserted here rather than one rule over every numeral.

What "published" means, mechanically
------------------------------------
Not a list in this file. `platform/build_release_notes.py` already owns the distinction: a
note whose first 4 KB contain `RELEASE-NOTE-FROZEN` belongs to a release that has been
published and the generator refuses to overwrite it; a note marked `RELEASE-NOTE-GENERATED`
is rebuilt from the artefacts on demand. So the published set is read from `docs/` under
exactly that rule, and a release becomes published here at the moment the author freezes its
note -- one edit, in the place the release actually happens.

The disclosure
--------------
When `VERSION` is not a published version, the tree is a version in preparation and every
surface that tells a reader how to cite must say so. The sentence is *derived* from the two
versions and required verbatim, so it cannot be half-corrected on one surface and left stale
on four -- which is the fan-out that produced this defect and the one before it.

    Version 1.1.0 is not yet deposited: it has no git tag and no version DOI. The most
    recent published release is v1.0.0, and the concept DOI resolves to that record until
    1.1.0 is published.

Run `--disclosure` to print the current text to paste.

Two surfaces deliberately do NOT carry it, and the reasons are not the same:

* `.zenodo.json` is the description of the *next* deposit. By the time anyone reads it on
  zenodo.org, the version it describes has been published, so a sentence saying that version
  is undeposited would be false exactly where it is read.
* `docs/RELEASE_NOTES_v*.md` is generated by `build_release_notes.py` and frozen on release;
  a hand-added sentence there would be erased by the next rebuild or would falsify a frozen
  record.

Scope
-----
Sources, not built documents. `docs/*.docx`, `*.pptx`, `*.pdf` and `*.html` are gitignored
reading copies that do not exist in a clone; the generators that wrote them are not published
here either, and every version string they interpolated came from `CITATION.cff` -- so the
stamp is caught here, at the source, whether or not anything downstream renders it. The same
reasoning `platform/check_metadata_counts.py` gives for scanning generators rather than their
output.

`prespec/`, `data/superseded/` and `memory/ledger/` are not scanned. A record of what was
registered or believed is never rewritten to match today.

Usage
-----
    ./.venv/bin/python platform/check_version_stamps.py
    ./.venv/bin/python platform/check_version_stamps.py --self-test
    ./.venv/bin/python platform/check_version_stamps.py --disclosure
    ./.venv/bin/python platform/check_version_stamps.py --root /path/to/scratch/tree
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

FROZEN_TOKEN = "RELEASE-NOTE-FROZEN"
#: Byte-for-byte `platform/build_release_notes.py`'s own test, window included. The token has
#: to OPEN an HTML comment: `docs/RELEASE_NOTES_v1.1.0.md` names it in its generated header
#: ("replace this marker with RELEASE-NOTE-FROZEN"), so a bare substring search reports the
#: unreleased version as published -- which is the one mistake that would make this whole
#: guard invert, requiring the disclosure to be REMOVED from a tree that still needs it.
FROZEN_RE = re.compile(r"<!--\s*" + FROZEN_TOKEN)
FROZEN_WINDOW = 4096

#: `\b` does not exist between "v" and "1", so a `\b`-anchored pattern reads "fixed to
#: v1.0.0" as naming no version at all -- and a pinned reference that names no version is
#: exactly what this guard reports as a defect. The `v` is part of how every one of these is
#: written.
SEMVER = re.compile(r"(?<![\w.])v?(\d+\.\d+\.\d+)(?![\w.])")
NOTE_NAME = re.compile(r"^RELEASE_NOTES_v(\d+\.\d+\.\d+)\.md$")
#: A GitHub URL that can only name a tag that has been pushed.
TAG_URL = re.compile(r"/(?:releases/tag|archive/refs/tags)/v(\d+\.\d+\.\d+)")
#: A GitHub URL naming a file on the default branch -- it follows the tree, not a tag.
BLOB_URL = re.compile(r"/blob/[^/]+/docs/RELEASE_NOTES_v(\d+\.\d+\.\d+)\.md")

#: The phrase that turned a correct fact into the false belief. "permanently fixed to v1.0.0"
#: was true; "(this release)" was what told the reader those were the bytes in front of them.
THIS_RELEASE = re.compile(r"\bthis release\b", re.I)

#: The shape of the disclosure, used to find a STALE one after a release has been cut.
DISCLOSURE_SHAPE = re.compile(r"Version (\d+\.\d+\.\d+) is not yet deposited")


def disclosure(current: str, published: str) -> str:
    """Derived from the two versions. Never typed, so it cannot go half-stale."""
    return (f"Version {current} is not yet deposited: it has no git tag and no version DOI. "
            f"The most recent published release is v{published}, and the concept DOI "
            f"resolves to that record until {current} is published.")


#: Surfaces that tell a reader how to cite THIS TREE. See the docstring for the two that are
#: excluded and why they are excluded for different reasons.
DISCLOSURE_SURFACES: tuple[str, ...] = (
    "CITATION.cff",
    "codemeta.json",
    "biotools.json",
    "README.md",
    "docs/REGISTRATION.md",
    # Generated from CITATION.cff by platform/build_dataset.py and rendered by app.js's
    # renderCitation() into the Provenance tab. Listed so that a rebuild that drops the
    # sentence is caught here rather than on the page.
    "data/dataset.json",
    "data/dataset.js",
)


@dataclass(frozen=True)
class Stamp:
    """One version string, and which of the two kinds it is."""
    path: str
    line: int
    where: str          # human-readable locator
    kind: str           # "identity" | "pinned"
    version: str
    raw: str = ""


def _line_of(text: str, needle: str) -> int:
    i = text.find(needle)
    return text.count("\n", 0, i) + 1 if i >= 0 else 0


def _norm(s: str) -> str:
    return " ".join(s.split())


#: Line-leading markers that wrap prose without being part of it. The disclosure has to be
#: findable inside a markdown blockquote, a YAML comment and a JS comment, because those are
#: the shapes the surfaces it must appear on actually hold prose in -- `docs/REGISTRATION.md`
#: carries it in a `>` block, and a whitespace-only normalisation reads every `>` as a word.
_PROSE_MARKER = re.compile(r"^[ \t]*(?:[>#*\-]+|//|;)[ \t]*")


def _flatten(text: str) -> str:
    """Whole file as one line, with quote and comment markers removed."""
    return " ".join(_PROSE_MARKER.sub("", line).strip() for line in text.splitlines())


# --------------------------------------------------------------------------- #
# What is published
# --------------------------------------------------------------------------- #

def published_versions(root: Path) -> list[str]:
    """Versions whose release note carries the FROZEN marker, newest last.

    Read from `docs/`, under `build_release_notes.py`'s own rule, so this file holds no list
    of releases that could go stale against the releases themselves.
    """
    out = []
    for p in sorted((root / "docs").glob("RELEASE_NOTES_v*.md")):
        m = NOTE_NAME.match(p.name)
        if not m:
            continue
        if FROZEN_RE.search(p.read_text(errors="replace")[:FROZEN_WINDOW]):
            out.append(m.group(1))
    return sorted(out, key=lambda v: tuple(int(x) for x in v.split(".")))


# --------------------------------------------------------------------------- #
# Reading the stamps
# --------------------------------------------------------------------------- #

def _cff(root: Path) -> tuple[dict, str]:
    import yaml
    text = (root / "CITATION.cff").read_text()
    return yaml.safe_load(text), text


def dois(root: Path) -> tuple[str, str]:
    """(concept DOI, version DOI), both read out of CITATION.cff rather than typed here.

    The concept DOI is the root `doi:` field. The version DOI is the one entry under
    `identifiers:` of type doi that is not it. If that is ever ambiguous the guard refuses
    rather than guessing which record a reader would be sent to.
    """
    d, _ = _cff(root)
    concept = str(d.get("doi") or "")
    others = [str(i.get("value")) for i in (d.get("identifiers") or [])
              if i.get("type") == "doi" and str(i.get("value")) != concept]
    if not concept or len(others) != 1:
        raise SystemExit(
            f"CITATION.cff must carry one concept DOI in `doi:` and exactly one other DOI "
            f"under `identifiers:`; found doi={concept!r} and others={others}. "
            "Refusing to guess which one is frozen to a release.")
    return concept, others[0]


def stamps(root: Path) -> list[Stamp]:
    """Every version stamp on every source surface, classified."""
    out: list[Stamp] = []
    concept, version_doi = dois(root)

    # ---- CITATION.cff --------------------------------------------------------
    d, text = _cff(root)
    out.append(Stamp("CITATION.cff", _line_of(text, f"version: {d.get('version')}"),
                     "`version:`", "identity", str(d.get("version"))))
    for ident in d.get("identifiers") or []:
        if str(ident.get("value")) != version_doi:
            continue
        desc = _norm(str(ident.get("description") or ""))
        m = SEMVER.search(desc)
        out.append(Stamp("CITATION.cff", _line_of(text, version_doi),
                         f"the description of version DOI {version_doi}", "pinned",
                         m.group(1) if m else "", desc))

    # ---- codemeta.json -------------------------------------------------------
    text = (root / "codemeta.json").read_text()
    cm = json.loads(text)
    out.append(Stamp("codemeta.json", _line_of(text, f'"version": "{cm.get("version")}"'),
                     "`version`", "identity", str(cm.get("version"))))
    rn = str(cm.get("releaseNotes") or "")
    if rn:
        # A tag URL is pinned to a pushed tag; a blob-on-main URL follows the tree.
        m = TAG_URL.search(rn)
        if m:
            out.append(Stamp("codemeta.json", _line_of(text, rn),
                             "`releaseNotes` (a tag URL)", "pinned", m.group(1), rn))
        else:
            m = BLOB_URL.search(rn)
            out.append(Stamp("codemeta.json", _line_of(text, rn),
                             "`releaseNotes` (an in-tree note)", "identity",
                             m.group(1) if m else "", rn))

    # ---- .zenodo.json --------------------------------------------------------
    text = (root / ".zenodo.json").read_text()
    zn = json.loads(text)
    out.append(Stamp(".zenodo.json", _line_of(text, f'"version": "{zn.get("version")}"'),
                     "`version` (governs the NEXT deposit)", "identity",
                     str(zn.get("version"))))

    # ---- biotools.json -------------------------------------------------------
    text = (root / "biotools.json").read_text()
    bt = json.loads(text)
    for v in bt.get("version") or []:
        out.append(Stamp("biotools.json", _line_of(text, f'"{v}"'),
                         "`version[]`", "identity", str(v)))
    for dl in bt.get("download") or []:
        url = str(dl.get("url") or "")
        m = TAG_URL.search(url)
        if m:
            out.append(Stamp("biotools.json", _line_of(text, url),
                             "`download[].url` (a tag URL)", "pinned", m.group(1), url))
            # The sibling field must describe the archive its own URL points at. These were
            # two hand-typed copies of one fact sitting three lines apart.
            if str(dl.get("version") or "") != m.group(1):
                out.append(Stamp("biotools.json", _line_of(text, url),
                                 "`download[].version` (must equal its own URL's tag)",
                                 "pinned", str(dl.get("version") or ""), url))
            else:
                out.append(Stamp("biotools.json", _line_of(text, url),
                                 "`download[].version`", "pinned", str(dl.get("version"))))
    for oid in bt.get("otherID") or []:
        if version_doi not in str(oid.get("value") or ""):
            continue
        raw = _norm(str(oid.get("version") or ""))
        m = SEMVER.search(raw)
        out.append(Stamp("biotools.json", _line_of(text, str(oid.get("value"))),
                         f"`otherID[].version` beside version DOI {version_doi}", "pinned",
                         m.group(1) if m else "", raw))

    # ---- README.md -----------------------------------------------------------
    text = (root / "README.md").read_text()
    for pat, where in (
        (re.compile(r"\(Version (\d+\.\d+\.\d+)\) \[Computer software\]"),
         "the how-to-cite blockquote"),
        (re.compile(r"version\s*=\s*\{(\d+\.\d+\.\d+)\}"), "the BibTeX block"),
    ):
        for m in pat.finditer(text):
            out.append(Stamp("README.md", text.count("\n", 0, m.start()) + 1, where,
                             "identity", m.group(1), _norm(m.group(0))))
    for m in re.finditer(r"permanently fixed to v(\d+\.\d+\.\d+)", text):
        out.append(Stamp("README.md", text.count("\n", 0, m.start()) + 1,
                         "the version-DOI paragraph", "pinned", m.group(1),
                         _norm(text[max(0, m.start() - 60):m.end() + 60])))

    # The command the documentation tells a reader to paste. `release.sh` itself refuses when
    # VERSION disagrees with its argument, so a stale number here does not cut the wrong
    # release -- it wastes the reader's next five minutes and, worse, is the number they will
    # then type by hand. Its own `usage:` line is deliberately NOT bound: that string is a
    # shape example, and the script validates the real argument against VERSION.
    for rel in ("README.md", "docs/REGISTRATION.md"):
        p = root / rel
        if not p.is_file():
            continue
        body = p.read_text()
        for m in re.finditer(r"\./release\.sh (\d+\.\d+\.\d+)", body):
            out.append(Stamp(rel, body.count("\n", 0, m.start()) + 1,
                             "the `./release.sh` command a reader is told to run", "identity",
                             m.group(1), _norm(m.group(0))))

    # ---- the generated citation block, and the page that renders it ----------
    for rel in ("data/dataset.json", "data/dataset.js"):
        p = root / rel
        if not p.is_file():
            continue
        text = p.read_text()
        body = text
        if rel.endswith(".js"):
            body = body[body.find("{"):].rstrip().rstrip(";")
        cit = (json.loads(body) or {}).get("citation") or {}
        if not cit:
            continue
        out.append(Stamp(rel, _line_of(text, f'"version": "{cit.get("version")}"'),
                         "`citation.version` (rendered on the Provenance tab)", "identity",
                         str(cit.get("version"))))
        for ident in cit.get("identifiers") or []:
            if str(ident.get("value")) != version_doi:
                continue
            desc = _norm(str(ident.get("description") or ""))
            m = SEMVER.search(desc)
            out.append(Stamp(rel, _line_of(text, version_doi),
                             f"`citation.identifiers[{version_doi}].description`", "pinned",
                             m.group(1) if m else "", desc))
    return out


# --------------------------------------------------------------------------- #
# The rules
# --------------------------------------------------------------------------- #

def judge(st: Stamp, current: str, published: list[str]) -> str | None:
    """The complaint about this stamp, or None."""
    if st.kind == "identity":
        if st.version != current:
            return (f"states {st.version or '(none)'}, VERSION says {current}. This stamp "
                    "describes the tree, so it follows VERSION.")
        return None
    # pinned
    if not st.version:
        return ("names no version at all. A pinned reference must say which published "
                "release it is fixed to, or a reader assumes it is this one.")
    if st.version not in published:
        return (f"names v{st.version}, which is not a published release "
                f"(published: {', '.join('v' + v for v in published) or 'none'}). A version "
                "DOI, a tag URL and a release tarball can only name a release that exists.")
    if st.version != current and THIS_RELEASE.search(st.raw or ""):
        return (f"names v{st.version} and calls it \"this release\" while VERSION is "
                f"{current}. That phrase is what told a reader the deposit in front of them "
                "was the tree in front of them.")
    return None


def disclosure_hits(root: Path, current: str, published: list[str]) -> list[tuple]:
    """(path, line, complaint) for the undeposited-version disclosure."""
    hits = []
    latest = published[-1] if published else ""
    want = disclosure(current, latest) if latest else ""
    for rel in DISCLOSURE_SURFACES:
        p = root / rel
        if not p.is_file():
            continue
        text = p.read_text(errors="replace")
        flat = _norm(_flatten(text))
        stale = [m for m in DISCLOSURE_SHAPE.finditer(text) if m.group(1) != current]
        for m in stale:
            hits.append((rel, text.count("\n", 0, m.start()) + 1,
                         f"a disclosure about version {m.group(1)}, but VERSION is {current}. "
                         "It was left behind by a release."))
        if current in published:
            for m in DISCLOSURE_SHAPE.finditer(text):
                if m.group(1) == current:
                    hits.append((rel, text.count("\n", 0, m.start()) + 1,
                                 f"says version {current} is not yet deposited, but its "
                                 "release note is frozen, so it is. Remove the sentence."))
            continue
        if not want:
            continue
        if _norm(want) not in flat:
            hits.append((rel, 0, "does not carry the undeposited-version disclosure. "
                                 "Run --disclosure for the exact sentence."))
    return hits


# --------------------------------------------------------------------------- #
# Self-test
# --------------------------------------------------------------------------- #

#: (kind, version, raw, must_complain). Each case is a state this guard has to separate,
#: and every one of them is a state some surface of this repository was actually in.
SELF_TEST: tuple[tuple[str, str, str, bool], ...] = (
    # The defect, in both halves.
    ("identity", "1.0.0", "", True),                      # CITATION.cff version: 1.0.0
    ("identity", "1.1.0", "", False),
    ("pinned", "1.0.0", "Version DOI -- permanently fixed to v1.0.0 (this release)", True),
    ("pinned", "1.0.0", "Version DOI -- permanently fixed to v1.0.0, published 2026-08-20",
     False),
    # The naive repair: rewriting every 1.0.0 to 1.1.0 relabels a frozen deposit.
    ("pinned", "1.1.0", "Version DOI -- permanently fixed to v1.1.0", True),
    # A pinned reference that names nothing is the same failure with the number removed.
    ("pinned", "", "Version DOI", True),
    # An identity stamp is allowed to say "this release" -- it IS this release.
    ("identity", "1.1.0", "v1.1.0 (this release)", False),
)


def self_test() -> int:
    current, published = "1.1.0", ["1.0.0"]
    failures = 0
    for kind, version, raw, must in SELF_TEST:
        st = Stamp("<self-test>", 0, "<self-test>", kind, version, raw)
        got = judge(st, current, published) is not None
        if got != must:
            print(f"  {'MISS' if must else 'FALSE POSITIVE'}  {kind} {version!r} {raw!r}\n"
                  f"        expected {'a complaint' if must else 'silence'}, got the other")
            failures += 1

    # The disclosure text is derived, so prove it is derived and not a constant.
    cases = [("1.1.0", "1.0.0"), ("2.0.0", "1.4.7")]
    for cur, pub in cases:
        s = disclosure(cur, pub)
        if f"Version {cur} is not yet deposited" not in s or f"v{pub}" not in s:
            print(f"  MISS  disclosure({cur!r}, {pub!r}) does not name both versions")
            failures += 1
        if not DISCLOSURE_SHAPE.search(s):
            print(f"  MISS  disclosure({cur!r}, {pub!r}) is not matched by its own shape, "
                  "so a stale one could never be found")
            failures += 1

    total = len(SELF_TEST) + 2 * len(cases) + len(cases)
    print(f"self-test: {total - failures} passed, {failures} failed")
    return failures


# --------------------------------------------------------------------------- #

def main(argv: list[str] | None = None) -> int:
    """`--root DIR` points every read at another tree, for the mutation suite."""
    global REPO
    argv = sys.argv[1:] if argv is None else argv
    if "--root" in argv:
        REPO = Path(argv[argv.index("--root") + 1]).resolve()
    if "--self-test" in argv:
        return 1 if self_test() else 0

    current = (REPO / "VERSION").read_text().strip()
    published = published_versions(REPO)
    if "--disclosure" in argv:
        print(disclosure(current, published[-1]) if published
              else "(no published release: nothing to disclose against)")
        return 0

    found = stamps(REPO)
    hits = [(s.path, s.line, f"{s.where} {why}") for s in found
            if (why := judge(s, current, published))]
    hits += disclosure_hits(REPO, current, published)

    print("=" * 78)
    print("version stamp guard: every stamp must name the version it is about")
    print("=" * 78)
    print(f"\nVERSION            {current}")
    print(f"published releases {', '.join('v' + v for v in published) or '(none)'}"
          f"   — read from {FROZEN_TOKEN} markers in docs/")
    print(f"state              {current} is "
          f"{'PUBLISHED' if current in published else 'IN PREPARATION (no tag, no DOI)'}")

    ident = sum(1 for s in found if s.kind == "identity")
    pin = sum(1 for s in found if s.kind == "pinned")
    files = len({s.path for s in found} | set(DISCLOSURE_SURFACES))
    print(f"\n{ident} identity stamp(s) and {pin} pinned reference(s) checked "
          f"across {files} surface(s)")

    if not hits:
        print("\nPASS — every stamp that describes this tree equals VERSION, every stamp "
              "pinned to a\npublished deposit names a release that exists, and the "
              "release state is disclosed.\n")
        return 0

    print(f"\nFAIL — {len(hits)} stamp(s) naming the wrong version:\n")
    for path, line, why in sorted(hits):
        print(f"  {path}:{line}" if line else f"  {path}")
        print(f"    {why}")
    print("\nAn IDENTITY stamp follows VERSION. A PINNED reference — a version DOI, a tag "
          "URL, a\nrelease tarball — names the published release it is frozen to, and must "
          "never be\nrelabelled to follow VERSION. Run --disclosure for the sentence every "
          "citation surface\nmust carry while VERSION is unreleased.\n")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
